---
- name: kill service
  hosts: all
  connection: ssh
  become: true
  tasks:
    - shell: "sudo kill -9 $(ps -ef|grep java|awk '$0 !~/grep/ {print $2}' |tr -s '\n' ' ')"
      ignore_errors: yes

- name: setup grpc producer
  hosts: rpc-server
  connection: ssh
  become: true
  tasks:
    - shell: "sh /root/rpc-benchmark/benchmark -c 32 -i 3 -t 10 -I 3 -T 10 -F 2 -p 8088 -f jmh.json /root/rpc-benchmark/grpc-benchmark/grpc-server > grpcserver.log 2>&1 & "
      async: 10
      poll: 10


- name: setup grpc consumer
  hosts: rpc-client
  connection: ssh
  become: true
  tasks:
   - name : setup grpc consumer
     set_fact: server="{{ groups['rpc-server']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|list }}"
   - shell: 'sh /root/rpc-benchmark/benchmark -c 60 -i 3 -t 10 -I 3 -T 10 -F 2 -s  {{ server[0]  }}   -p 8088 -f jmh.json /root/rpc-benchmark/grpc-benchmark/grpc-client > grpcclient.log '

- name: get result
  hosts: rpc-client
  connection: ssh
  become: true
  tasks:
    - name : fetched result from client
      fetch:
        src: /root/jmh.json
        dest: ../../result/grpc/grpc_benchmark.json
        flat: yes