---
- name: kill service
  hosts: all
  connection: ssh
  become: true
  tasks:
    - shell: "kill -9 $(ps -ef|grep java|awk '$0 !~/grep/ {print $2}' |tr -s '\n' ' ')"
      ignore_errors: yes

- name: setup thrift server
  hosts: rpc-server
  connection: ssh
  become: true
  tasks:
    - name : setup thrift client
      set_fact: server="{{ groups['rpc-server']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|list }}"
    - shell: "sh /root/rpc-benchmark/benchmark  -p 8088 -s  {{ server[0]  }} /root/rpc-benchmark/thrift-benchmark/thrift-server > thriftserver.log 2>&1 & "
      async: 10
      poll: 10


- name: setup thrift client
  hosts: rpc-client
  connection: ssh
  become: true
  tasks:
   - name : setup thrift client
     set_fact: server="{{ groups['rpc-server']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|list }}"
   - shell: 'sh /root/rpc-benchmark/benchmark -c 32 -i 3 -t 10 -I 3 -T 10 -F 2 -s  {{ server[0]  }}   -p 8088 -f jmh.json /root/rpc-benchmark/thrift-benchmark/thrift-client > thriftclient.log '

- name: get result
  hosts: rpc-client
  connection: ssh
  become: true
  tasks:
    - name : fetched result from client
      fetch:
        src: /root/jmh.json
        dest: ../../result/thrift/thrift_benchmark.json
        flat: yes